name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          # - windows-latest
        ocaml-version:
          - 4.12.x
          - 4.11.x
          - 4.10.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-local-packages: |
            *.opam

      - run: opam depext owl-ode-base owl-ode owl-ode-odepack --with-test
    
      - run: |
          opam install owl-ode-base --yes --deps-only --with-test
          opam exec -- dune build -p owl-ode-base
          opam exec -- dune runtest -p owl-ode-base
  
      - run: |
          opam install owl-ode --yes --deps-only --with-test
          opam exec -- dune build -p owl-ode
          opam exec -- dune runtest -p owl-ode
  
      - run: |
          opam install owl-ode-sundials --yes --deps-only --with-test
          opam exec -- dune build -p owl-ode-sundials
          opam exec -- dune runtest -p owl-ode-sundials
  
      - run: |
           opam install owl-ode-odepack --yes --deps-only --with-test
           opam exec -- dune build -p owl-ode-odepack 
           opam exec -- dune runtest -p owl-ode-odepack
